drm: samsung: panel: fix build with missing debugfs includes (v6.10 preparation)
Linux commit [1] stopped including debugfs.h via drm_print.h.

This causes compilation of this driver to fail:

    .../samsung/panel/panel-samsung-drv.c:2336:2: error: call to undeclared function 'debugfs_create_file'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     2336 |         debugfs_create_file(name, 0600, parent, (void *)cmdset, &panel_cmdset_fops);
          |         ^
    .../samsung/panel/panel-samsung-drv.c:2363:2: error: call to undeclared function 'debugfs_create_u32'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     2363 |         debugfs_create_u32("rev", 0600, parent, &ctx->panel_rev);
          |         ^
    etc.

Update the code here accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=33d5ae6cacf4 [1]
      ("drm/print: drop include debugfs.h and include where needed")
Fixes: 33d5ae6cacf4 ("drm/print: drop include debugfs.h and include where needed")
Test: TH
Bug: 353965155
Change-Id: I37a2e389cca642cb9d57a16e657714438de08a06
Signed-off-by: André Draszik <draszik@google.com>