samsung/exynos_drm_decon.h: fix compilation for CONFIG_EXYNOS_BTS=n
With CONFIG_ECT disabled, this file doesn't compile:

    In file included from samsung/cal_9845/decon_reg.c:21:
    samsung/cal_9845/../exynos_drm_decon.h:540:6: error: no previous prototype for ‘decon_mode_bts_pre_update’ [-Werror=missing-prototypes]
      540 | void decon_mode_bts_pre_update(struct decon_device *decon,
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~

Mark it as static inline to allow compilation.

Test: TH, locally compile without CONFIG_EXYNOS_BTS
Fixes: 21459df80d7d ("drm: samsung: update bw early if new mode fps is higher")
Bug: 423391571
Change-Id: I6b7f65d541492c134342320edd1b15474eff4457
Signed-off-by: André Draszik <draszik@google.com>